CREATE TABLE IF NOT EXISTS `order` (
    `id` INT PRIMARY KEY AUTO_INCREMENT,
    `order_number` VARCHAR(32) NOT NULL UNIQUE,
    `sender_id` INT NOT NULL,
    `order_time` DATETIME NOT NULL,
    `paid_amount` DECIMAL(10,2) NOT NULL,
    `payment_method` ENUM('CASH', 'CARD', 'TRANSFER') NOT NULL,
    `shipping_address` TEXT NOT NULL,
    `delivery_address` TEXT NOT NULL,
    `recipient_lastname` VARCHAR(255) NOT NULL,
    `recipient_firstname` VARCHAR(255) NOT NULL,
    `recipient_phone` VARCHAR(15) NOT NULL,
    `weight` INT NOT NULL,
    `delivery_level` ENUM('STANDARD', 'EXPRESS') NOT NULL,
    `deliverer_id` INT,
    `relay_point_id` INT,
    FOREIGN KEY (`sender_id`) REFERENCES `user`(`id`),
    FOREIGN KEY (`deliverer_id`) REFERENCES `user`(`id`),
    FOREIGN KEY (`relay_point_id`) REFERENCES `storage`(`id`)
);